### ISSUE TITLE
Output the size in mo instead of mb

### ISSUE THREAD

**Issue by francoiscabrol** [GreGosPhaTos/bigfile#4]
I was expecting --outputSize giving the size in mega-octets instead of mega-bytes...
Should not be hard to change... what do you think?

**Comment by GreGosPhaTos** [comment]
Yes, it's legit I though since we do searching for huge files the MB output was making more sense. 
But, definitely I can add this value to the results.

**Comment by francoiscabrol** [comment]
https://www.differencebetween.com/difference-between-octet-and-vs-byte/ it looks like octet is prefered over bytes. If I am talking about that it's because I got a different value in the output than using `du` and was confused... but after having check again, it's your tool that print the good value! (I get the same value in the file finder).
